### PR TITLE
Adds vi key bindings.

### PR DESCRIPTION
**Pull request by freuk**
That one set of default bindings, maybe you think it's useful. Let me know if you want me to de-duplicate the code.

### CODE REVIEW

**Comment by emilaxelsson** [comment]
Thank you!

Could you please write something about this in the [README](../blob/master/README.md)? It could be brief.

I think the code is fine for now, but feel free to de-duplicate if you have the time.

**Comment by emilaxelsson** [comment]
```haskell
 stepApp _ _ s (VtyEvent (EvKey (KChar 'd') [MCtrl])) = theView `vScrollBy` 25 >> continue s
```

Is scrolling by 25 lines a standard Vi thing?

**Comment by freuk** [comment]
Yes it is :dancer: 
~~is ViewPatterns fine?~~ nevermind, I missed that from your `.cabal`

**Comment by freuk** [comment]
I wrote it with guards finally, and played around with the build, which seemed to work fine. I hope I didn't break your software. :) Thanks.

**Comment by emilaxelsson** [comment]
That looks very good. Thank you!

**Comment by emilaxelsson** [comment]
I've uploaded a new version on Hackage.

**Pull request merged**
